export interface ILgaList {
  id: string;
  name: string;
  stateId: string;
  stateCode?: string;
  newName?: string;
  agentCode?: string;
  senatorialDistrictId: string;
}

export const LgaList: ILgaList[] = [
  {
    id: "1",
    name: "ABA NORTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "2",
    name: "ABA SOUTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "3",
    name: "AROCHUKWU",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "4",
    name: "BENDE",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "5",
    name: "IKWUANO",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "6",
    name: "ISIALA NGWA NORTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "7",
    name: "ISIALA NGWA SOUTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "8",
    name: "ISUIKWUATO",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "9",
    name: "OBINGWA",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "10",
    name: "OHAFIA",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "11",
    name: "OSISIOMA",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "12",
    name: "UGWUNAGBO",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "13",
    name: "UKWA WEST",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "14",
    name: "UKWA EAST",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "15",
    name: "UMU - NNEOCHI",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "16",
    name: "UMUAHIA SOUTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "17",
    name: "UMUAHIA NORTH",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "18",
    name: "DEMSA",
    stateId: "1",
    senatorialDistrictId: "NULL",
  },
  {
    id: "19",
    name: "DEMSA",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "20",
    name: "FUFURE",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "21",
    name: "GANYE",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "22",
    name: "GAYUK",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "23",
    name: "GIREI",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "24",
    name: "GOMBI",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "25",
    name: "LAMURDE",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "26",
    name: "HONG",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "27",
    name: "JADA",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "28",
    name: "MADAGALI",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "29",
    name: "MAIHA",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "30",
    name: "MAYO BELWA",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "31",
    name: "MICHIKA",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "32",
    name: "MUBI NORTH",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "33",
    name: "MUBI SOUTH",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "34",
    name: "NUMAN",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "35",
    name: "SHELLENG",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "36",
    name: "SONG",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "37",
    name: "TOUNGO",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "38",
    name: "YOLA NORTH",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "39",
    name: "YOLA SOUTH",
    stateId: "2",
    senatorialDistrictId: "NULL",
  },
  {
    id: "40",
    name: "ABAK",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "41",
    name: "EASTERN OBOLO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "42",
    name: "EKET",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "43",
    name: "ESIT EKET (UQUO)",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "44",
    name: "ESSIEN UDIM",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "45",
    name: "ETIM EKPO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "46",
    name: "ETINAN",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "47",
    name: "IBENO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "48",
    name: "IBESIKPO ASUTAN",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "49",
    name: "IBIONO IBOM",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "50",
    name: "IKA",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "51",
    name: "IKONO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "52",
    name: "IKOT ABASI",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "53",
    name: "IKOT EKPENE",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "54",
    name: "INI",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "55",
    name: "ITU",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "56",
    name: "MBO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "57",
    name: "MKPAT ENIN",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "58",
    name: "NSIT ATAI",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "59",
    name: "NSIT IBOM",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "60",
    name: "NSIT UBIUM",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "61",
    name: "OBOT AKARA",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "62",
    name: "OKOBO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "63",
    name: "ONNA",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "64",
    name: "ORON",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "65",
    name: "ORUK ANAM",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "66",
    name: "UDUNG UKO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "67",
    name: "UKANAFUN",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "68",
    name: "URUAN",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "69",
    name: "URUE OFFONG ORUKO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "70",
    name: "UYO",
    stateId: "3",
    senatorialDistrictId: "NULL",
  },
  {
    id: "71",
    name: "AGUATA",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "72",
    name: "ANAMBRA EAST",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "73",
    name: "ANAMBRA WEST",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "74",
    name: "ANAOCHA",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "75",
    name: "AWKA NORTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "76",
    name: "AWKA SOUTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "77",
    name: "AYAMELUM",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "78",
    name: "DUNUKOFIA",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "79",
    name: "EKWUSIGO",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "80",
    name: "EKWUSIGO",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "81",
    name: "IDEMILI NORTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "82",
    name: "IDEMILI SOUTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "83",
    name: "IHALA",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "84",
    name: "NJIKOKA",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "85",
    name: "NNEWI NORTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "86",
    name: "NNEWI SOUTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "87",
    name: "OGBARU",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "88",
    name: "ONITSHA SOUTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "89",
    name: "ONITSHA NORTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "90",
    name: "ORUMBA NORTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "91",
    name: "ORUMBA SOUTH",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "92",
    name: "OYI",
    stateId: "4",
    senatorialDistrictId: "NULL",
  },
  {
    id: "93",
    name: "BOGORO",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "94",
    name: "ALKALERI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "95",
    name: "BAUCHI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "96",
    name: "DAMBAM",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "97",
    name: "DARAZO",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "98",
    name: "DASS",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "99",
    name: "GAMAWA",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "100",
    name: "GANJUWA",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "101",
    name: "GIADE",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "102",
    name: "ITAS/GADAU",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "103",
    name: "JAMA'ARE",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "104",
    name: "KATAGUM",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "105",
    name: "KIRFI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "106",
    name: "MISAU",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "107",
    name: "NINGI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "108",
    name: "SHIRA",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "109",
    name: "TAFAWA BALEWA",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "110",
    name: "TORO",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "111",
    name: "WARJI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "112",
    name: "ZAKI",
    stateId: "5",
    senatorialDistrictId: "NULL",
  },
  {
    id: "113",
    name: "BRASS",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "114",
    name: "EKEROMOR",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "115",
    name: "KOLOKUMA/OPOKUMA",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "116",
    name: "NEMBE",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "117",
    name: "OGBIA",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "118",
    name: "SAGBAMA",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "119",
    name: "SOUTHERN IJAW",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "120",
    name: "YENAGOA",
    stateId: "6",
    senatorialDistrictId: "NULL",
  },
  {
    id: "121",
    name: "ADO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "122",
    name: "AGATU",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "123",
    name: "APA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "124",
    name: "BURUKU",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "125",
    name: "GBOKO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "126",
    name: "GUMA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "127",
    name: "GWER EAST",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "128",
    name: "GWER WEST",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "129",
    name: "KATSINA-ALA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "130",
    name: "KONSHISHA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "131",
    name: "KWANDE",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "132",
    name: "LOGO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "133",
    name: "MAKURDI",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "134",
    name: "OBI",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "135",
    name: "OGBADIBO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "136",
    name: "OHIMINI",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "137",
    name: "OJU",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "138",
    name: "OKPOKWU",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "139",
    name: "OTUKPO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "140",
    name: "TARKA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "141",
    name: "UKUM",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "142",
    name: "USHONGO",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "143",
    name: "VANDEIKYA",
    stateId: "7",
    senatorialDistrictId: "NULL",
  },
  {
    id: "144",
    name: "ABADAM",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "145",
    name: "ASKIRA/UBAH",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "146",
    name: "BAMA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "147",
    name: "BAYO",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "148",
    name: "BIU",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "149",
    name: "CHIBOK",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "150",
    name: "DAMBOA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "151",
    name: "DIKWA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "152",
    name: "GUBIO",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "153",
    name: "GUZAMALA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "154",
    name: "GWOZA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "155",
    name: "HAWUL",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "156",
    name: "JERE",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "157",
    name: "KAGA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "158",
    name: "KALA BALGE",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "159",
    name: "KONDUGA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "160",
    name: "KUKAWA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "161",
    name: "KWAYA / KUSAR",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "162",
    name: "MAFA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "163",
    name: "MAGUMERI",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "164",
    name: "MAIDUGURI M. C.",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "165",
    name: "MARTE",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "166",
    name: "MOBBAR",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "167",
    name: "MONGUNO",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "168",
    name: "NGALA",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "169",
    name: "NGANZAI",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "170",
    name: "SHANI",
    stateId: "8",
    senatorialDistrictId: "NULL",
  },
  {
    id: "171",
    name: "ABI",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "172",
    name: "AKAMKPA",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "173",
    name: "AKPABUYO",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "174",
    name: "BAKASSI",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "175",
    name: "BEKWARRA",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "176",
    name: "BIASE",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "177",
    name: "BOKI",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "178",
    name: "CALABAR MUNICIPALITY",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "179",
    name: "CALABAR SOUTH",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "180",
    name: "ETUNG",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "181",
    name: "IKOM",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "182",
    name: "OBANLIKU",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "183",
    name: "OBUBRA",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "184",
    name: "OBUDU",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "185",
    name: "ODUKPANI",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "186",
    name: "OGOJA",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "187",
    name: "YAKURR",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "188",
    name: "YALA",
    stateId: "9",
    senatorialDistrictId: "NULL",
  },
  {
    id: "189",
    name: "ANIOCHA - SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "190",
    name: "ANIOCHA NORTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "191",
    name: "BOMADI",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "192",
    name: "BURUTU",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "193",
    name: "ETHIOPE EAST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "194",
    name: "ETHIOPE WEST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "195",
    name: "IKA - SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "196",
    name: "IKA NORTH- EAST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "197",
    name: "ISOKO NORTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "198",
    name: "ISOKO SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "199",
    name: "NDOKWA EAST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "200",
    name: "NDOKWA WEST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "201",
    name: "OKPE",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "202",
    name: "OSHIMILI - NORTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "203",
    name: "OSHIMILI - SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "204",
    name: "PATANI",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "205",
    name: "SAPELE",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "206",
    name: "UDU",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "207",
    name: "UGHELLI NORTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "208",
    name: "UGHELLI SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "209",
    name: "UKWUANI",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "210",
    name: "WARRI NORTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "211",
    name: "WARRI SOUTH",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "212",
    name: "WARRI SOUTH WEST",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "213",
    name: "ABAKALIKI",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "214",
    name: "AFIKPO SOUTH",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "215",
    name: "AFIKPO NORTH",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "216",
    name: "EBONYI",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "217",
    name: "EZZA NORTH",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "218",
    name: "EZZA SOUTH",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "219",
    name: "IKWO",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "220",
    name: "ISHIELU",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "221",
    name: "IVO",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "222",
    name: "IZZI",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "223",
    name: "OHAOZARA",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "224",
    name: "OHAUKWU",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "225",
    name: "ONICHA",
    stateId: "11",
    senatorialDistrictId: "NULL",
  },
  {
    id: "226",
    name: "AKOKO EDO",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "227",
    name: "EGOR",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "228",
    name: "ESAN CENTRAL",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "229",
    name: "ESAN NORTH EAST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "230",
    name: "ESAN SOUTH EAST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "231",
    name: "ESAN WEST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "232",
    name: "ETSAKO WEST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "233",
    name: "ETSAKO CENTRAL",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "234",
    name: "ETSAKO EAST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "235",
    name: "IGUEBEN",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "236",
    name: "IKPOBA/OKHA",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "237",
    name: "OREDO",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "238",
    name: "ORHIONMWON",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "239",
    name: "OVIA NORTH EAST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "240",
    name: "OVIA SOUTH WEST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "241",
    name: "OWAN EAST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "242",
    name: "OWAN WEST",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "243",
    name: "UHUNMWODE",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "244",
    name: "UVWIE",
    stateId: "10",
    senatorialDistrictId: "NULL",
  },
  {
    id: "245",
    name: "ADO EKITI",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "246",
    name: "EFON",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "247",
    name: "EKITI EAST",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "248",
    name: "EKITI SOUTH WEST",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "249",
    name: "EKITI WEST",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "250",
    name: "EMURE",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "251",
    name: "GBONYIN",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "252",
    name: "IDO / OSI",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "253",
    name: "IJERO",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "254",
    name: "IKERE",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "255",
    name: "IKOLE",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "256",
    name: "ILEJEMEJE",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "257",
    name: "IREPODUN / IFELODUN",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "258",
    name: "ISE / ORUN",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "259",
    name: "MOBA",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "260",
    name: "OYE",
    stateId: "13",
    senatorialDistrictId: "NULL",
  },
  {
    id: "261",
    name: "ANINRI",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "262",
    name: "AWGU",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "263",
    name: "ENUGU EAST",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "264",
    name: "ENUGU NORTH",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "265",
    name: "ENUGU SOUTH",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "266",
    name: "EZEAGU",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "267",
    name: "IGBO ETITI",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "268",
    name: "IGBO EZE NORTH",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "269",
    name: "IGBO EZE SOUTH",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "270",
    name: "ISI UZO",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "271",
    name: "NKANU EAST",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "272",
    name: "NKANU WEST",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "273",
    name: "NSUKKA",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "274",
    name: "OJI-RIVER",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "275",
    name: "UDENU",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "276",
    name: "UDI",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "277",
    name: "UZO-UWANI",
    stateId: "14",
    senatorialDistrictId: "NULL",
  },
  {
    id: "278",
    name: "AKKO",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "279",
    name: "BALANGA",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "280",
    name: "BILLIRI",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "281",
    name: "DUKKU",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "282",
    name: "FUNAKAYE",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "283",
    name: "GOMBE",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "284",
    name: "KALTUNGO",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "285",
    name: "KWAMI",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "286",
    name: "NAFADA",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "287",
    name: "SHONGOM",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "288",
    name: "YALMALTU/ DEBA",
    stateId: "15",
    senatorialDistrictId: "NULL",
  },
  {
    id: "289",
    name: "ABOH MBAISE",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "290",
    name: "AHIAZU MBAISE",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "291",
    name: "EHIME MBANO",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "292",
    name: "EZINIHITTE MBAISE",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "293",
    name: "IDEATO NORTH",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "294",
    name: "IDEATO SOUTH",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "295",
    name: "IHITTE/UBOMA (ISINWEKE)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "296",
    name: "IKEDURU (IHO)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "297",
    name: "ISIALA MBANO (UMUELEMAI)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "298",
    name: "ISU (UMUNDUGBA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "299",
    name: "MBAITOLI (NWAORIEUBI)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "300",
    name: "NGOR OKPALA (UMUNEKE)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "301",
    name: "NJABA (NNENASA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "302",
    name: "NKWERRE",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "303",
    name: "NWANGELE (ONU-NWANGELE AMAIGBO)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "304",
    name: "OBOWO (OTOKO)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "305",
    name: "OGUTA (OGUTA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "306",
    name: "OHAJI/EGBEMA (MMAHU-EGBEMA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "307",
    name: "OKIGWE (OKIGWE)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "308",
    name: "ONUIMO (OKWE)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "309",
    name: "ORLU",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "310",
    name: "ORSU (AWO IDEMILI)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "311",
    name: "ORU WEST (MGBIDI)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "312",
    name: "ORU-EAST",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "313",
    name: "OWERRI NORTH (ORIE URATTA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "314",
    name: "OWERRI URBAN (OWERRI)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "315",
    name: "OWERRI WEST (UMUGUMA)",
    stateId: "16",
    senatorialDistrictId: "NULL",
  },
  {
    id: "316",
    name: "AUYO",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "317",
    name: "BABURA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "318",
    name: "BIRNIN KUDU",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "319",
    name: "BIRNIWA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "320",
    name: "BUJI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "321",
    name: "DUTSE",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "322",
    name: "GAGARAWA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "323",
    name: "GARKI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "324",
    name: "GUMEL",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "325",
    name: "GURI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "326",
    name: "GWARAM",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "327",
    name: "GWIWA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "328",
    name: "HADEJIA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "329",
    name: "JAHUN",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "330",
    name: "KAFIN HAUSA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "331",
    name: "KAUGAMA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "332",
    name: "KAZAURE",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "333",
    name: "KIRIKA SAMMA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "334",
    name: "KIYAWA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "335",
    name: "MAIGATARI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "336",
    name: "MALAM MADORI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "337",
    name: "MIGA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "338",
    name: "RINGIM",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "339",
    name: "RONI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "340",
    name: "SULE-TANKARKAR",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "341",
    name: "TAURA",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "342",
    name: "YANKWASHI",
    stateId: "17",
    senatorialDistrictId: "NULL",
  },
  {
    id: "343",
    name: "BIRNIN GWARI",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "344",
    name: "CHIKUN",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "345",
    name: "GWIWA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "346",
    name: "IGABI",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "347",
    name: "IKARA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "348",
    name: "JABA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "349",
    name: "JEMA'A",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "350",
    name: "KACHIA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "351",
    name: "KADUNA NORTH",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "352",
    name: "KADUNA SOUTH",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "353",
    name: "KAGARKO",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "354",
    name: "KAJURU",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "355",
    name: "KAURA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "356",
    name: "KAURU",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "357",
    name: "KUBAU",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "358",
    name: "KUDAN",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "359",
    name: "LERE",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "360",
    name: "MAKARFI",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "361",
    name: "SABON GARI",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "362",
    name: "SANGA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "363",
    name: "SOBA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "364",
    name: "ZANGON KATAF",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "365",
    name: "ZARIA",
    stateId: "18",
    senatorialDistrictId: "NULL",
  },
  {
    id: "366",
    name: "AJINGI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "367",
    name: "ALBASU",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "368",
    name: "BAGWAI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "369",
    name: "BEBEJI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "370",
    name: "BICHI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "371",
    name: "BUNKURE",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "372",
    name: "DALA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "373",
    name: "DANBATTA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "374",
    name: "DAWAKI KUDU",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "375",
    name: "DAWAKI TOFA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "376",
    name: "DOGUWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "377",
    name: "FAGGE",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "378",
    name: "GABASAWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "379",
    name: "GARKO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "380",
    name: "GURUN MALAM",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "381",
    name: "GAYA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "382",
    name: "GEZAWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "383",
    name: "GWALE",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "384",
    name: "GWARZO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "385",
    name: "KABO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "386",
    name: "KANO MUNICIPAL",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "387",
    name: "KARAYE",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "388",
    name: "KIBIYA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "389",
    name: "KIRU",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "390",
    name: "KUMBOTSO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "391",
    name: "KUNCHI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "392",
    name: "KURA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "393",
    name: "MADOBI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "394",
    name: "MAKODA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "395",
    name: "MINJIBIR",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "396",
    name: "NASARAWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "397",
    name: "RANO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "398",
    name: "RIMIN GADO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "399",
    name: "ROGO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "400",
    name: "SHANONO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "401",
    name: "SUMAILA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "402",
    name: "TAKAI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "403",
    name: "TARAUNI",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "404",
    name: "TOFA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "405",
    name: "TSANYAWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "406",
    name: "TUDUN WADA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "407",
    name: "UNGOGO",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "408",
    name: "WARAWA",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "409",
    name: "WUDIL",
    stateId: "19",
    senatorialDistrictId: "NULL",
  },
  {
    id: "410",
    name: "BAKORI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "411",
    name: "BATAGARAWA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "412",
    name: "BATSARI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "413",
    name: "BAURE",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "414",
    name: "BINDAWA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "415",
    name: "CHARANCHI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "416",
    name: "DANMUSA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "417",
    name: "DANDUME",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "418",
    name: "DANJA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "419",
    name: "DAURA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "420",
    name: "DUTSI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "421",
    name: "DUTSIN-MA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "422",
    name: "FASKARI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "423",
    name: "FUNTUA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "424",
    name: "INGAWA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "425",
    name: "JIBIA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "426",
    name: "KAFUR",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "427",
    name: "KAITA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "428",
    name: "KANKARA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "429",
    name: "KANKIA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "430",
    name: "KATSINA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "431",
    name: "KURFI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "432",
    name: "KUSADA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "433",
    name: "MAI'ADUA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "434",
    name: "MALUFASHI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "435",
    name: "MANI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "436",
    name: "MASHI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "437",
    name: "MATAZU",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "438",
    name: "MUSAWA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "439",
    name: "RIMI",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "440",
    name: "SABUWA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "441",
    name: "SAFANA",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "442",
    name: "SANDAMU",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "443",
    name: "ZANGO",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "444",
    name: "SANDAMU",
    stateId: "20",
    senatorialDistrictId: "NULL",
  },
  {
    id: "445",
    name: "ALIERO",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "446",
    name: "AREWA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "447",
    name: "ARGUNGU",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "448",
    name: "AUGIE",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "449",
    name: "BAGUDO",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "450",
    name: "BIRNIN KEBBI",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "451",
    name: "BUNZA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "452",
    name: "DANDI",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "453",
    name: "FAKAI",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "454",
    name: "GWANDU",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "455",
    name: "JEGA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "456",
    name: "KALGO",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "457",
    name: "KOKO BESSE",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "458",
    name: "MAIYAMA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "459",
    name: "NGASKI",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "460",
    name: "SAKABA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "461",
    name: "SHANGA",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "462",
    name: "SURU",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "463",
    name: "WASAGU/DANKO",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "464",
    name: "YAURI",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "465",
    name: "ZURU",
    stateId: "21",
    senatorialDistrictId: "NULL",
  },
  {
    id: "466",
    name: "ADAVI",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "467",
    name: "AJAOKUTA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "468",
    name: "ANKPA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "469",
    name: "BASSA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "470",
    name: "DEKINA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "471",
    name: "IBAJI",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "472",
    name: "IDAH",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "473",
    name: "IGALAMELA/ODOLU",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "474",
    name: "IJUMU",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "475",
    name: "KABBA/BUNU",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "476",
    name: "KOGI . K. K.",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "477",
    name: "LOKOJA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "478",
    name: "MOPA MORO",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "479",
    name: "OFU",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "480",
    name: "OGORI MANGO",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "481",
    name: "OKEHI",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "482",
    name: "OKENE",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "483",
    name: "OLAMABORO",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "484",
    name: "OMALA",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "485",
    name: "YAGBA EAST",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "486",
    name: "YAGBA WEST",
    stateId: "22",
    senatorialDistrictId: "NULL",
  },
  {
    id: "487",
    name: "ASA",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "488",
    name: "BARUTEN",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "489",
    name: "EDU",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "490",
    name: "EKITI",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "491",
    name: "IFELODUN",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "492",
    name: "ILLORIN EAST",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "493",
    name: "ILORIN-SOUTH",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "494",
    name: "ILORIN-WEST",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "495",
    name: "IREPODUN",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "496",
    name: "ISIN",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "498",
    name: "MORO",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "499",
    name: "OFFA",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "500",
    name: "OKE-ERO",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "501",
    name: "OYUN",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "502",
    name: "PATIGI",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
  {
    id: "503",
    name: "AGEGE",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "504",
    name: "AJEROMI/IFELODUN",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "505",
    name: "ALIMOSHO",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "506",
    name: "AMUWO-ODOFIN",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "507",
    name: "APAPA",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "508",
    name: "BADAGRY",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "509",
    name: "EPE",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "510",
    name: "ETI-OSA",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "511",
    name: "IBEJU/LEKKI",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "512",
    name: "IFAKO-IJAYE",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "513",
    name: "IKEJA",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "514",
    name: "IKORODU",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "515",
    name: "KOSOFE",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "516",
    name: "LAGOS ISLAND",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "517",
    name: "LAGOS MAINLAND",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "518",
    name: "MUSHIN",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "519",
    name: "OSHO",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "520",
    name: "OSHODI/ISOLO",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "521",
    name: "SOMOLU",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "522",
    name: "SURULERE",
    stateId: "24",
    senatorialDistrictId: "NULL",
  },
  {
    id: "523",
    name: "AKWANGA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "524",
    name: "AWE",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "525",
    name: "DOMA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "526",
    name: "KARU",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "527",
    name: "KEANA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "528",
    name: "KEFFI",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "529",
    name: "KOKONA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "530",
    name: "LAFIA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "531",
    name: "NASSARAWA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "532",
    name: "NASARAWA EGGON",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "533",
    name: "OBI",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "534",
    name: "TOTO",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "535",
    name: "WAMBA",
    stateId: "25",
    senatorialDistrictId: "NULL",
  },
  {
    id: "537",
    name: "AGAIE",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "538",
    name: "AGWARA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "539",
    name: "BIDA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "540",
    name: "BORGU",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "541",
    name: "BOSSO",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "542",
    name: "CHANCHAGA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "543",
    name: "EDATTI",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "544",
    name: "GBAKO",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "545",
    name: "GURARA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "546",
    name: "KATCHA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "547",
    name: "KONTAGORA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "548",
    name: "LAPAI",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "549",
    name: "LAVUN",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "550",
    name: "MAGAMA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "551",
    name: "MARIGA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "552",
    name: "MASHEGU",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "553",
    name: "MOKWA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "554",
    name: "MUNYA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "555",
    name: "PAIKORO",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "556",
    name: "RAFI",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "557",
    name: "RIJAU",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "558",
    name: "SHIRORO",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "559",
    name: "SULEJA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "560",
    name: "TAFA",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "561",
    name: "WUSHISHI",
    stateId: "26",
    senatorialDistrictId: "NULL",
  },
  {
    id: "562",
    name: "ABEOKUTA NORTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "563",
    name: "ABEOKUTA SOUTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "564",
    name: "ADO ODO-OTA",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "565",
    name: "EGBADO NORTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "566",
    name: "EGBADO SOUTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "567",
    name: "EWEKORO",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "568",
    name: "IFO",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "569",
    name: "IJEBU EAST",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "570",
    name: "IJEBU NORTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "571",
    name: "IJEBU NORTH EAST",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "572",
    name: "IJEBU ODE",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "573",
    name: "IKENNE",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "574",
    name: "IMEKO/AFON",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "575",
    name: "IPOKIA",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "576",
    name: "OBAFEMI/OWODE",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "577",
    name: "ODEDA",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "578",
    name: "ODOGBOLU",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "579",
    name: "OGUN WATER SIDE",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "580",
    name: "REMO NORTH",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "581",
    name: "SAGAMU",
    stateId: "27",
    senatorialDistrictId: "NULL",
  },
  {
    id: "582",
    name: "AKOKO NORTH EAST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "583",
    name: "AKOKO NORTH WEST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "584",
    name: "AKOKO SOUTH EAST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "585",
    name: "AKOKO SOUTH WEST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "586",
    name: "AKURE NORTH",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "587",
    name: "AKURE SOUTH",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "588",
    name: "ESE-ODO",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "589",
    name: "IDANRE",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "590",
    name: "IFEDORE",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "591",
    name: "ILAJE",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "592",
    name: "ILEOLUJI/OKEIGBO",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "593",
    name: "IRELE",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "594",
    name: "ODIGBO",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "595",
    name: "OKITIPUPA",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "596",
    name: "ONDO EAST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "597",
    name: "ONDO WEST",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "598",
    name: "OSE",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "599",
    name: "OWO",
    stateId: "28",
    senatorialDistrictId: "NULL",
  },
  {
    id: "600",
    name: "ATAKUMOSA EAST",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "601",
    name: "ATAKUMOSA WEST",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "602",
    name: "AYEDAADE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "603",
    name: "AYEDIRE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "604",
    name: "BOLUWADURO",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "605",
    name: "BORIPE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "606",
    name: "EDE NORTH",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "607",
    name: "EDE SOUTH",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "608",
    name: "EGBEDORE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "609",
    name: "EJIGBO",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "610",
    name: "IFE CENTRAL",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "611",
    name: "IFE EAST",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "612",
    name: "IFE NORTH",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "613",
    name: "IFE SOUTH",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "614",
    name: "IFEDAYO",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "615",
    name: "IFELODUN",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "616",
    name: "ILA",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "617",
    name: "ILESA EAST",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "618",
    name: "ILESA WEST",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "619",
    name: "IREPODUN",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "620",
    name: "IREWOLE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "621",
    name: "ISOKAN",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "622",
    name: "IWO",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "623",
    name: "OBOKUN",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "624",
    name: "ODO-OTIN",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "625",
    name: "OLA-OLUWA",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "626",
    name: "OLORUNDA",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "627",
    name: "ORIADE",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "628",
    name: "OROLU",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "629",
    name: "OSOGBO",
    stateId: "29",
    senatorialDistrictId: "NULL",
  },
  {
    id: "630",
    name: "AFIJIO",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "631",
    name: "AKINYELE",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "632",
    name: "ATIBA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "633",
    name: "ATISBO",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "634",
    name: "EGBEDA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "635",
    name: "IBADAN NORTH",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "636",
    name: "IBADAN NORTH EAST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "637",
    name: "IBADAN SOUTH WEST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "638",
    name: "IBADAN NORTH-WEST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "639",
    name: "IBADAN SOUTH-EAST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "640",
    name: "IBARAPA CENTRAL",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "641",
    name: "IBARAPA EAST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "642",
    name: "IBARAPA NORTH",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "643",
    name: "IDO",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "644",
    name: "IREPO",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "645",
    name: "ISEYIN",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "646",
    name: "ITESIWAJU",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "647",
    name: "IWAJOWA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "648",
    name: "KAJOLA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "649",
    name: "LAGELU",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "650",
    name: "OGBOMOSO NORTH",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "651",
    name: "OGBOMOSO SOUTH",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "652",
    name: "OGO-OLUWA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "653",
    name: "OLORUNSOGO",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "654",
    name: "OLUYOLE",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "655",
    name: "ONA-ARA",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "656",
    name: "OORELOPE",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "657",
    name: "ORI IRE",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "658",
    name: "OYO EAST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "659",
    name: "OYO WEST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "660",
    name: "SAKI EAST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "661",
    name: "SAKI WEST",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "662",
    name: "SURULERE",
    stateId: "30",
    senatorialDistrictId: "NULL",
  },
  {
    id: "663",
    name: "BARIKIN LADI",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "664",
    name: "BASSA",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "665",
    name: "BOKKOS",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "666",
    name: "JOS EAST",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "667",
    name: "JOS NORTH",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "668",
    name: "JOS SOUTH",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "669",
    name: "KANAM",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "670",
    name: "KANKE",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "671",
    name: "LANGTANG NORTH",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "672",
    name: "LANGTANG SOUTH",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "673",
    name: "MANGU",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "674",
    name: "MIKANG",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "675",
    name: "PANKSHIN",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "676",
    name: "QUA'AN PAN",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "677",
    name: "RIYOM",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "678",
    name: "SHENDAM",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "679",
    name: "WASE",
    stateId: "31",
    senatorialDistrictId: "NULL",
  },
  {
    id: "680",
    name: "ABUA-ODUAL",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "681",
    name: "AHOADA EAST",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "682",
    name: "AHOADA WEST",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "683",
    name: "AKUKU TORU",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "684",
    name: "ANDONI",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "685",
    name: "ASARI-TORU",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "686",
    name: "BONNY",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "687",
    name: "DEGEMA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "688",
    name: "ELEME",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "689",
    name: "EMOHUA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "690",
    name: "ETCHE",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "691",
    name: "GOKANA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "692",
    name: "IKWERRE",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "693",
    name: "KHANA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "694",
    name: "OBIO/AKPOR",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "695",
    name: "OGBA/EGBEMA/NDONI",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "696",
    name: "OGU/BOLO",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "697",
    name: "OKRIKA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "698",
    name: "OMUMA",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "699",
    name: "OPOBO/NEKORO",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "700",
    name: "OYIGBO",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "701",
    name: "PORT HARCOURT",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "702",
    name: "TAI",
    stateId: "32",
    senatorialDistrictId: "NULL",
  },
  {
    id: "703",
    name: "BINJI",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "704",
    name: "BODINGA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "705",
    name: "DANGE/SHUNI",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "706",
    name: "GADA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "707",
    name: "GORONYO",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "708",
    name: "GUDU",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "709",
    name: "GWADABAWA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "710",
    name: "ILLELA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "711",
    name: "ISA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "712",
    name: "KEBBE",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "713",
    name: "KWARE",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "714",
    name: "RABAH",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "715",
    name: "S/BIRNI",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "716",
    name: "SHAGARI",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "717",
    name: "SILAME",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "718",
    name: "SOKOTO NORTH",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "719",
    name: "SOKOTO SOUTH",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "720",
    name: "TAMBUWAL",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "721",
    name: "TANGAZA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "722",
    name: "TURETA",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "723",
    name: "WAMAKKO",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "724",
    name: "WURNO",
    stateId: "33",
    senatorialDistrictId: "NULL",
  },
  {
    id: "726",
    name: "YABO",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "727",
    name: "ARDO - KOLA",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "728",
    name: "BALI",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "729",
    name: "DONGA",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "730",
    name: "GASHAKA",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "731",
    name: "GASSOL",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "732",
    name: "IBI",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "733",
    name: "JALINGO",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "734",
    name: "KARIM-LAMIDO",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "735",
    name: "KURMI",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "736",
    name: "LAU",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "737",
    name: "SARDAUNA",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "738",
    name: "TAKUM",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "739",
    name: "USSA",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "740",
    name: "WUKARI",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "741",
    name: "YORRO",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "742",
    name: "ZING",
    stateId: "34",
    senatorialDistrictId: "NULL",
  },
  {
    id: "743",
    name: "BADE",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "744",
    name: "BURSARI",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "745",
    name: "DAMATURU",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "746",
    name: "FIKA",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "747",
    name: "FUNE",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "748",
    name: "GEIDAM",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "749",
    name: "GUJBA",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "750",
    name: "GULANI",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "752",
    name: "JAKUSKO",
    stateId: "12",
    senatorialDistrictId: "NULL",
  },
  {
    id: "753",
    name: "JAKUSKO",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "754",
    name: "KARASAWA",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "761",
    name: "MACHINA",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "762",
    name: "NANGERE",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "763",
    name: "NGURU",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "764",
    name: "POTISKUM",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "765",
    name: "TARMUWA",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "766",
    name: "YUNUSARI",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "767",
    name: "YUSUFARI",
    stateId: "35",
    senatorialDistrictId: "NULL",
  },
  {
    id: "768",
    name: "ANKA",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "769",
    name: "BAKURA",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "770",
    name: "BIRNIN MAGAJI",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "771",
    name: "BUKKUYUM",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "772",
    name: "BUNGUDU",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "773",
    name: "GUMMI",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "774",
    name: "GUSAU",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "775",
    name: "KAURA NAMODA",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "776",
    name: "MARADUN",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "777",
    name: "MARU",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "778",
    name: "SHINKAFI",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "779",
    name: "TALATA MAFARA",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "780",
    name: "TSAFE",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "781",
    name: "ZURMI",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "782",
    name: "ABAJI",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "783",
    name: "BWARI",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "784",
    name: "GWAGWALADA",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "785",
    name: "KUJE",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "786",
    name: "KWALI",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "787",
    name: "MUNICIPAL",
    stateId: "37",
    senatorialDistrictId: "NULL",
  },
  {
    id: "788",
    name: "ANKA",
    stateId: "36",
    senatorialDistrictId: "NULL",
  },
  {
    id: "793",
    name: "KAIAMA",
    stateId: "23",
    senatorialDistrictId: "NULL",
  },
];
